# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Landing
    url: https://firectmusic.ru
  - name: API
    url: https://fmlk.firectmusic.ru/api
  - name: FMLK
    url: https://fmlk.firectmusic.ru/

status-website:
  cname: status.firectmusic.ru
  logoUrl: https://firectmusic.ru/assets/images/logo-1.png
  name: Firect Music Status
