owner: eitherdigital
repo: upptime

sites:
  - name: Landing
    url: https://either.digital
  - name: API
    url: https://lk.either.digital/api/v1/status
  - name: LK
    url: https://lk.either.digital

status-website:
  cname: status.either.digital
  logoUrl: https://raw.githubusercontent.com/eitherdigital/upptime/master/firectlogo.svg
  name: Either Digital Status

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
