owner: firectmusic
repo: upptime

sites:
  - name: Landing
    url: https://firectmusic.ru
  - name: API
    url: https://fmlk.firectmusic.ru/api/v1/status
  - name: FMLK
    url: https://fmlk.firectmusic.ru/

status-website:
  cname: status.firectmusic.ru
  logoUrl: https://raw.githubusercontent.com/firectmusic/upptime/master/firectlogo.svg
  name: Firect Music Status
