owner: eitherdigital
repo: upptime

sites:
  - name: Landing
    url: https://either.digital
  - name: API
    url: https://api.either.digital/status
  - name: LK
    url: https://lk.either.digital
  - name: Dev
    url: https://dev.either.digital
  - name: Smart Links
    url: https://links.either.digital
  - name: Smart Links LK
    url: https://llk.either.digital
  - name: SQL Browser
    url: https://sql.either.digital

status-website:
  cname: status.either.digital
  logoUrl: https://raw.githubusercontent.com/eitherdigital/upptime/master/assets/either-logo.svg
  name: Either Digital Status

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
